### ISSUE TITLE
Bugs after #2

### ISSUE THREAD

**Issue by xxkfqz** [jaspwr/vol-applet#3]
Thanks for respond and quick fix. Really useful for me! But I found two bugs in new version (d8ef05dcb3a9eb2818d1efd8cac05e56940d0641)

## 1. Position shifts after expanding/collapsing groups
Steps to reproduce:

1. Expand all groups
![Screenshot_20230725_200537](https://github.com/jaspwr/vol-applet/assets/52203435/f117de25-7f7e-4fe6-b01a-6b4dcaa2c727)
2. Collapse any group
![Screenshot_20230725_200546](https://github.com/jaspwr/vol-applet/assets/52203435/dc28f6da-cc17-492e-8044-0022c479f6a0)

Bug presents on IceWM v3.4.1. Not so critical like next one

## 2. Crash if stream contains characters from East Asian writing systems

Steps to reproduce:
1. Open some video with japanese in title ([example](https://youtu.be/yhD9lThziz0))
2. Left click on icon in tray _or_ launch `volapplet -isc` when stream already presents

```shell
$ RUST_BACKTRACE=full ./target/debug/volapplet -isc
thread 'main' panicked at 'byte index 30 is not a char boundary; it is inside '】' (bytes 28..31) of `【東方Darksynth/Synthwave】 Violet Delta - Race to the Crescent Moon - YouTube`', src/elements.rs:142:21
stack backtrace:
   0:     0x555b8653e6b7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5753212a473df300
   1:     0x555b8655f98f - core::fmt::write::haa21365a9a54c2bc
   2:     0x555b8653c927 - std::io::Write::write_fmt::h590a96b42012b60f
   3:     0x555b8653e4c5 - std::sys_common::backtrace::print::h35a5c8ca123167ed
   4:     0x555b8653f857 - std::panicking::default_hook::{{closure}}::h57c276781cc3ef55
   5:     0x555b8653f644 - std::panicking::default_hook::h671191bc9834a0dc
   6:     0x555b8653fd0c - std::panicking::rust_panic_with_hook::h524ae7efd61bd530
   7:     0x555b8653fc07 - std::panicking::begin_panic_handler::{{closure}}::h777f35af96143ef6
   8:     0x555b8653eae6 - std::sys_common::backtrace::__rust_end_short_backtrace::hf7e0e85b2defac61
   9:     0x555b8653f952 - rust_begin_unwind
  10:     0x555b864c03f3 - core::panicking::panic_fmt::hf06df6a1d47564fe
  11:     0x555b86562dec - core::str::slice_error_fail_rt::he83fcf180e95c78a
  12:     0x555b864c0b77 - core::str::slice_error_fail::hd90f3d705571b066
  13:     0x555b864ca213 - core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::RangeTo<usize>>::index::h90432d91394b781a
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/str/traits.rs:309:21
  14:     0x555b864ca213 - core::str::traits::<impl core::ops::index::Index<I> for str>::index::h8134805efa883d2b
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/str/traits.rs:61:15
  15:     0x555b864ca213 - <alloc::string::String as core::ops::index::Index<core::ops::range::RangeTo<usize>>>::index::hdc2c1cc28787d415
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/string.rs:2358:10
  16:     0x555b864df973 - volapplet::elements::substring_name::h9e9cd238a51247ec
                               at /home/xxkfqz/src/vol-applet/src/elements.rs:142:23
  17:     0x555b864dec0f - volapplet::elements::VolumeSlider::new::hfaf91e3571848655
                               at /home/xxkfqz/src/vol-applet/src/elements.rs:32:25
  18:     0x555b864dcc49 - volapplet::popout::Popout::append_volume_slider::h666957b6835f7732
                               at /home/xxkfqz/src/vol-applet/src/popout.rs:205:9
  19:     0x555b864ddce8 - volapplet::popout::create_grouped::h63502c8b37693a21
                               at /home/xxkfqz/src/vol-applet/src/popout.rs:296:17
  20:     0x555b864dd313 - volapplet::popout::add_outputs_from_list::hf43bc11dd815cf32
                               at /home/xxkfqz/src/vol-applet/src/popout.rs:263:9
  21:     0x555b864e9eb1 - volapplet::popout::Popout::update_outputs::{{closure}}::h768b1a1ce7399df3
                               at /home/xxkfqz/src/vol-applet/src/popout.rs:186:13
  22:     0x555b864e1786 - glib::source::fnmut_callback_wrapper::{{closure}}::hdaffc3c76baad5d6
                               at /home/xxkfqz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.16.7/src/source.rs:256:9
  23:     0x555b864e0d2f - glib::source::trampoline::h290d7dc44b22a490
                               at /home/xxkfqz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.16.7/src/source.rs:112:5
  24:     0x7f9c535a6579 - g_main_context_dispatch
  25:     0x7f9c535a6998 - <unknown>
  26:     0x7f9c535a6a2c - g_main_context_iteration
  27:     0x7f9c5292c4fd - g_application_run
  28:     0x555b864eac1b - <O as gio::application::ApplicationExtManual>::run_with_args::haf4eda5e1a8bf0fd
                               at /home/xxkfqz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.16.7/src/application.rs:35:13
  29:     0x555b864ce26b - volapplet::run::h41cc1596145e791f
                               at /home/xxkfqz/src/vol-applet/src/lib.rs:39:5
  30:     0x555b864c0d97 - volapplet::main::h73864106b40762fe
                               at /home/xxkfqz/src/vol-applet/src/main.rs:4:5
  31:     0x555b864c0d5b - core::ops::function::FnOnce::call_once::h772236686d8ac54d
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  32:     0x555b864c0d7e - std::sys_common::backtrace::__rust_begin_short_backtrace::h0c7e72330bb3edc4
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:135:18
  33:     0x555b864c0cd1 - std::rt::lang_start::{{closure}}::hdfedd49c89ed4e68
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:166:18
  34:     0x555b86539533 - std::rt::lang_start_internal::h21ceffb2fc8dcb57
  35:     0x555b864c0caa - std::rt::lang_start::hc51a9fd0756e8326
                               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:165:17
  36:     0x555b864c0dbe - main
  37:     0x7f9c5259b9ca - __libc_start_call_main
                               at /usr/src/debug/sys-libs/glibc-2.37-r3/glibc-2.37/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  38:     0x7f9c5259ba85 - __libc_start_main_impl
                               at /usr/src/debug/sys-libs/glibc-2.37-r3/glibc-2.37/csu/../csu/libc-start.c:360:3
  39:     0x555b864c0ba1 - _start
  40:                0x0 - <unknown>
```

**Comment by jaspwr** [comment]
Sorry about this. I'll fix these tomorrow.

**Comment by jaspwr** [comment]
This should be resolved. Thank you for reporting.
